server:
  port: 8761
spring:
  application:
    name: naming-server
    
# false é para ele não se auto registrar em outras instancia de eureka server
eureka:
  client:
    register-with-eureka: false 
    fetch-registry: false
