server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mariadb://localhost:3306/
    schemas:
    - cambio_service
    user: root
    password: root
  sleuth: #usado para log de microserviços
    sampler:
      probability: 1.0 #vai logar 100% de tudo. Pode defnir por exemplo: 0.05 que seria 5%
      
#Usado para que o swagger UI no gateway consiga achar o json do swagger nessa aplicação
#Usado para que o swagger UI no gateway consiga achar o json do swagger nessa aplicação
springdoc:
  api-docs:
    path: cambio-service/v3/api-docs
