server:
  port: 8080
spring:
  application:
    name: greeting-service
  config:
    import:
    - optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: prod
    
#Liberando todos os recursos do spring actuator (Não é recomendado deixar tudo exposto em produção)
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
