server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: cambio-service
        uri: lb://cambio-service
        predicates:
        - Path=/cambio-service/**
      - id: book-service
        uri: lb://book-service
        predicates:
        - Path=/book-service/**
      - id: api-gateway
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  sleuth: #usado para log de microserviços
    sampler:
      probability: 1.0 #vai logar 100% de tudo. Pode defnir por exemplo: 0.05 que seria 5%