server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j: # resilience4j é o substituto do Hystrix
  bulkhead: #para chamadas concorrentes
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter: #Limitar a quantidade de chamada em um método
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry: #Tentativas de executar o método novamente em caso de falha
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true #a primeira requisição dura 1, depois 2, depois 3 depois 5, depois 8 (+- fibonacci)
      default:
        max-attempts: 7
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mariadb://localhost:3306/
    schemas:
    - book_service
    user: root
    password: root
  sleuth: #usado para log de microserviços
    sampler:
      probability: 1.0 #vai logar 100% de tudo. Pode defnir por exemplo: 0.05 que seria 5%
  zipkin:
    base-url: http://127.0.0.1:9411/ #não precisa configurar o zipkin (portal para checar os logs) por que a configuração já é default
#Usado para que o swagger UI no gateway consiga achar o json do swagger nessa aplicação
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs